### ISSUE TITLE
Tiled map -> Empirica map

### ISSUE THREAD

**Issue by rcalcott9** [nataliavelez/playable_lines#6]
Description: The player should see a map with the following features:
- a sprite that can move across the grid in response to pressing keys
- 'natural' obstacles that are collidable (rocks, plants, etc)
- a well or water source that is collidable and has the 'source' property, which enables sprites to interact with the water. If the player presses the space bar, they should acquire a water icon above their head. 
- A set of plants that have the 'target' property. When the player presses the space bar next to the plants, a watering can icon should appear and the water icon should disappear. 
- A boundary feature should appear around the perimeter of the board (to prevent the sprite interacting with the actual edge of the board
- Multiple other sprites should appear on the board in the multiplayer mode

Status: So far, we've implemented the 'universalization necessary' map for a single player version of the game. 

Todo:
Create maps corresponding to the high (x3), low (x3), and medium (x1) universalization categories
Integrate them into the Empirica site and enable a randomization function

**Comment by WhiteJP** [comment]
Rachel has now completed this :). Closing issue.
